### PR TITLE
Update from dist

### PR DESCRIPTION
**Pull request by pezholio**
Updated from the latest upstream version of Swagger UI

### CODE REVIEW

**Comment by dblock** [comment]
Was this run via `bundle exec rake swagger_ui:dist:update`?

**Comment by pezholio** [comment]
Yep, I think there might be an issue with the command as it took out a bunch of stuff I needed in the application.js, so there was some manual fiddling too.

**Comment by dblock** [comment]
That's what I meant. Check out https://github.com/ruby-grape/grape-swagger-rails/blob/master/lib/tasks/swagger_ui.rake#L23. It needs to be updated along with the distribution changes so that we can just run it next time. Now that you have a good, updated state it should be fairly easy, you can run it, look at changes it made on top of this, update the task, run again, until all you have left is the changes in the task. Could you please do that?

**Comment by pezholio** [comment]
Ah, gotcha. No probs, will do that now

**Comment by pezholio** [comment]
@dblock That's done now - the rake task now leaves me with a clean working directory, so all should be golden 👍

**Comment by dblock** [comment]
Perfect. Merging.

**Pull request merged**
