### PR TITLE
fix #markdown-toc table of content Indentation

### PR DESCRIPTION
**Pull request by TangMonk**
also see #28

### CODE REVIEW

**Comment by dblock** [comment]
Good. Please add to CHANGELOG. 

Double-check that running `rake swagger_ui:dist:update` preserves this change.

**Comment by dblock** [comment]
Bump.

**Comment by dblock** [comment]
Bump @TangMonk.

**Comment by TangMonk** [comment]
closed

**Comment by dblock** [comment]
Closed? Does this not fix anything @TangMonk ?

**Pull request closed without merging**
