### PR TITLE
Headers added before  swaggerUi.load() call.

### PR DESCRIPTION
**Pull request by sedx**
My application use auth by headers content.
When Swagger UI fetch source from swagger documentation path it return 401 because headers sets after call _swaggerUI.load()_ and request for swagger documentation dosen't include auth headers.

In my version headers sets in initialize swaggerUI object and when _swaggerUI.load() _call request for fetch documantation include header

### CODE REVIEW

**Comment by dblock** [comment]
I would be OK with this change. It needs a CHANGELOG entry and the commits squashed, please.

**Comment by sedx** [comment]
@dblock Done

**Comment by dblock** [comment]
I dug this a bit more. Why is the subsequent call to `window.swaggerUi.api.clientAuthorizations.add` not adding the headers? It's supposed to work and I know people rely on that behavior. Is this https://github.com/ruby-grape/grape-swagger-rails/issues/13?

**Comment by sedx** [comment]
@dblock No `window.swaggerUi.api.clientAuthorizations.add` works fine, but all API call in my application need auth headers X-Client  and X-Secret (request swagger docs too).
Ui can't get swagger_documantation.json on page load  because `clientAuthorizations.add` call after `swaggerUi.load()`, and first request has no required auth headers.

**Comment by dblock** [comment]
Oh I see @sedx, this is much more trivial than I thought. I'll merge this.

**Pull request merged**
