### PR TITLE
Add test matrix for multiple Ruby versions & update dependencies

### PR DESCRIPTION
**Pull request by duffn**
This adds a test matrix for multiple versions of Ruby and `grape-swagger`.

I've tried to leave as much the same as I could, but some changes were necessary and I've also made a few guesses here:

- Support Ruby 2.7+
- Support `grape-swagger` >= 1.6.0
	- The old matrix had very old versions of the package, the most recent being from June 2019. I can add some more recent versions to the matrix if requested and can see what happens, but am not sure how many different versions we want to support.
- Support `railties` >= 6

## Other notes

- Added inflections initializer for `Failure/Error: mount API => '/'`
- Sorted Gemfile
- Updated `mime-types` for error on Ruby 3 ` SyntaxError: /home/runner/work/grape-swagger-rails/grape-swagger-rails/vendor/bundle/ruby/3.0.0/gems/mime-types-2.99.3/lib/mime/types/logger.rb:26: _1 is reserved for numbered 
parameter`
- Added `webrick` for Ruby 3
- Update `rack` to solve resolution conflicts
- gemspec rubocop formatting
- Update GitHub Actions versions

## TODO

- [x] Branched off of https://github.com/ruby-grape/grape-swagger-rails/pull/105 so get that merged first
- [x] Danger broke because I force pushed? Or because it's a fork? https://github.com/danger/danger/issues/1103

### CODE REVIEW

**Comment by dblock** [comment]
Add fetch-depth like https://github.com/slack-ruby/slack-ruby-bot-server/blob/master/.github/workflows/danger.yml#L10, should fix danger.

**Comment by dblock** [comment]
Shall we increment the version to 0.4.0 and make a release? Want to help @duffn, remind me your Rubygems username?

**Comment by duffn** [comment]
@dblock Yeah, sounds good. It’s the same username.

**Comment by dblock** [comment]
Added you!

**Comment by duffn** [comment]
Accepted, thanks!

**Pull request merged**
