### PR TITLE
Support CSS media queries

### PR DESCRIPTION
**Pull request by alexagranov**
Just needed the proper <meta> tag

### CODE REVIEW

**Comment by dblock** [comment]
Please update https://github.com/ruby-grape/grape-swagger-rails/blob/master/CHANGELOG.md too, via `--amend`.

**Comment by alexagranov** [comment]
Was able to replicate the earlier spec failures by downgrading my FF.  Adding ``` sleep 1 ``` does the trick with selenium_webdriver sometimes, although I know ``` find ``` shouldn't timeout so quickly. (shrug)

Current CI problems look to be 2.0.0 and 1.9.3 gem installation issues.

**Comment by dblock** [comment]
Indeed, sleep is definitely not the way to go. Lets worry about the build separately.

**Comment by dblock** [comment]
Merged via https://github.com/ruby-grape/grape-swagger-rails/commit/0c9c65a4486e94f595525a686b52b64b5bbb014b. 

I fixed the build issue by locking mime-types to < 3.0 in https://github.com/ruby-grape/grape-swagger-rails/commit/6293c7c8d09883d1329b9a2bb1725053d3fcb3e5, same as we did in Grape.

**Comment by dblock** [comment]
Build fixed in https://github.com/ruby-grape/grape-swagger-rails/pull/40, disabled animations to avoid the sleeps.

**Comment by alexagranov** [comment]
Excellent!  Thanks for the quick turnaround and tip off to https://github.com/mikz/rack-no_animations

**Pull request closed without merging**
