### PR TITLE
Change #before_filter to #before_action

### LINKED ISSUE #62: Deprecation warning in Rails5
```
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from block (2 levels) in <module:ClassMethods> at /Users/moe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/abstract_controller/callbacks.rb:191)
Processing by GrapeSwaggerRails::ApplicationController#index as HTML
  Rendering /Users/moe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/grape-swagger-rails-0.2.1/app/views/grape_swagger_rails/application/index.html.erb
```

### PR DESCRIPTION
**Pull request by m-o-e**
Closes #62

### CODE REVIEW

**Comment by dblock** [comment]
The problem here is that it's not backward compatible. For starters we definitely would need something like https://github.com/ruby-grape/grape-swagger/blob/master/UPGRADING.md here that explains what to do when upgrading. 

I would actually prefer that the public interface cleanly deprecates the old method, ie. writes the old one in terms of the new one with a DEPRECATED warning, first.

It needs a CHANGELOG entry, too.

**Comment by m-o-e** [comment]
Sorry, I agree with your concerns but won't have time to work on this anytime soon.
Feel free to take this PR as a starting point or close it in favor to a better fix.

**Comment by dblock** [comment]
Thanks for your help @m-o-e, if someone wants to finish this, see ^^^.

**Comment by serggl** [comment]
made a followup PR here: #70

**Comment by dblock** [comment]
Closing in favor of https://github.com/ruby-grape/grape-swagger-rails/pull/70.

**Pull request closed without merging**
